-- MySQL Script generated by MySQL Workbench
-- Fri May 15 18:36:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema prodven_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prodven_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prodven_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `prodven_db` ;

-- -----------------------------------------------------
-- Table `prodven_db`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`empresas` (
  `id_empresa` CHAR(36) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `slogan` VARCHAR(255) NULL DEFAULT NULL,
  `logo_url` TEXT NULL DEFAULT NULL,
  `nit` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `pais` VARCHAR(100) NOT NULL DEFAULT 'Colombia',
  `modo` ENUM('privado', 'publico') NOT NULL DEFAULT 'privado',
  `tienda_activa` TINYINT(1) NOT NULL DEFAULT '0',
  `plan` ENUM('gratuito', 'basico', 'premium', 'enterprise') NOT NULL DEFAULT 'gratuito',
  `color_primario` VARCHAR(7) NULL DEFAULT '#0A2A43',
  `color_secundario` VARCHAR(7) NULL DEFAULT '#27AE60',
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `razon_social` VARCHAR(200) NULL DEFAULT NULL,
  `tipo_documento` VARCHAR(20) NULL DEFAULT NULL,
  `telefono_secundario` VARCHAR(20) NULL DEFAULT NULL,
  `departamento` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(20) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `descripcion_corta` VARCHAR(255) NULL DEFAULT NULL,
  `categoria` VARCHAR(100) NULL DEFAULT NULL,
  `sitio_web` VARCHAR(255) NULL DEFAULT NULL,
  `redes_sociales` TEXT NULL DEFAULT NULL,
  `logo_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `portada_url` TEXT NULL DEFAULT NULL,
  `portada_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `horario_atencion` JSON NULL DEFAULT NULL,
  `modo_publico` TINYINT(1) NULL DEFAULT NULL,
  `acepta_domicilios` TINYINT(1) NULL DEFAULT NULL,
  `acepta_recoger_en_tienda` TINYINT(1) NULL DEFAULT NULL,
  `calificacion_promedio` DECIMAL(3,2) NULL DEFAULT NULL,
  `total_resenas` INT NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_verificacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `email` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `nit` (`nit` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`usuarios` (
  `id_usuario` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NULL DEFAULT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `clave_hash` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  `rol` ENUM('superadmin', 'administrador', 'vendedor', 'produccion', 'supervisor', 'cliente') NOT NULL DEFAULT 'cliente',
  `verificado` TINYINT(1) NOT NULL DEFAULT '0',
  `two_factor_activo` TINYINT(1) NOT NULL DEFAULT '0',
  `two_factor_secret` VARCHAR(255) NULL DEFAULT NULL,
  `ultimo_acceso` DATETIME NULL DEFAULT NULL,
  `intentos_fallidos` INT NOT NULL DEFAULT '0',
  `bloqueado_hasta` DATETIME NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `idx_usuario_correo` (`correo` ASC) VISIBLE,
  INDEX `idx_usuario_rol` (`rol` ASC) VISIBLE,
  INDEX `idx_usuario_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`clientes` (
  `id_cliente` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NULL DEFAULT NULL,
  `empresa` VARCHAR(150) NULL DEFAULT NULL,
  `nit` VARCHAR(20) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `genero` ENUM('masculino', 'femenino', 'otro', 'prefiero_no_decir') NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`),
  INDEX `idx_cliente_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_cliente_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`categorias` (
  `id_categoria` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `imagen_url` TEXT NULL DEFAULT NULL,
  `orden` INT NOT NULL DEFAULT '0',
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_categoria`),
  INDEX `idx_categoria_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`proveedores` (
  `id_proveedor` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `contacto` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `nit` VARCHAR(20) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_proveedor`),
  INDEX `idx_proveedor_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`productos` (
  `id_producto` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_categoria` CHAR(36) NULL DEFAULT NULL,
  `id_proveedor` CHAR(36) NULL DEFAULT NULL,
  `codigo_sku` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  `costo` DECIMAL(12,2) NULL DEFAULT NULL,
  `cantidad_stock` INT NOT NULL DEFAULT '0',
  `nivel_reorden` INT NOT NULL DEFAULT '5',
  `unidad` VARCHAR(30) NOT NULL DEFAULT 'unidad',
  `publicado` TINYINT(1) NOT NULL DEFAULT '0',
  `destacado` TINYINT(1) NOT NULL DEFAULT '0',
  `permite_contra_entrega` TINYINT(1) NOT NULL DEFAULT '1',
  `tiempo_preparacion_min` INT NOT NULL DEFAULT '0',
  `calificacion_promedio` DECIMAL(3,2) NOT NULL DEFAULT '0.00',
  `total_resenas` INT NOT NULL DEFAULT '0',
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `codigo_sku` (`codigo_sku` ASC) VISIBLE,
  INDEX `fk_producto_proveedor` (`id_proveedor` ASC) VISIBLE,
  INDEX `idx_producto_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_producto_publicado` (`publicado` ASC) VISIBLE,
  INDEX `idx_producto_categoria` (`id_categoria` ASC) VISIBLE,
  FULLTEXT INDEX `idx_producto_busqueda` (`nombre`, `descripcion`) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `prodven_db`.`categorias` (`id_categoria`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `prodven_db`.`proveedores` (`id_proveedor`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`promociones` (
  `id_promocion` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NULL DEFAULT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `tipo` ENUM('porcentaje', 'valor_fijo', '2x1', 'envio_gratis') NOT NULL,
  `valor` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `codigo` VARCHAR(50) NULL DEFAULT NULL,
  `uso_maximo` INT NULL DEFAULT NULL,
  `uso_actual` INT NOT NULL DEFAULT '0',
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_promocion`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE,
  INDEX `fk_promocion_producto` (`id_producto` ASC) VISIBLE,
  INDEX `idx_promocion_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_promocion_codigo` (`codigo` ASC) VISIBLE,
  CONSTRAINT `fk_promocion_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_promocion_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`carrito` (
  `id_carrito` CHAR(36) NOT NULL,
  `id_cliente` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_promocion` CHAR(36) NULL DEFAULT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `descuento` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `costo_domicilio` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `total` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `estado` ENUM('activo', 'abandonado', 'convertido') NOT NULL DEFAULT 'activo',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_carrito`),
  INDEX `fk_carrito_promocion` (`id_promocion` ASC) VISIBLE,
  INDEX `idx_carrito_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_carrito_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `prodven_db`.`clientes` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_carrito_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_carrito_promocion`
    FOREIGN KEY (`id_promocion`)
    REFERENCES `prodven_db`.`promociones` (`id_promocion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`codigos_verificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`codigos_verificacion` (
  `id_codigo` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `tipo` ENUM('verificacion_correo', 'recuperacion_password', '2fa', 'cambio_correo') NOT NULL,
  `usado` TINYINT(1) NOT NULL DEFAULT '0',
  `intentos` INT NOT NULL DEFAULT '0',
  `fecha_expiracion` DATETIME NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_codigo`),
  INDEX `idx_codigo_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_codigo_expiracion` (`fecha_expiracion` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`configuracion_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`configuracion_empresa` (
  `id_configuracion` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `permite_contra_entrega` TINYINT(1) NULL DEFAULT '1',
  `permite_pagos_digitales` TINYINT(1) NULL DEFAULT '1',
  `permite_pedidos_programados` TINYINT(1) NULL DEFAULT '1',
  `radio_domicilio_km` DECIMAL(5,2) NULL DEFAULT '5.00',
  `costo_domicilio` DECIMAL(12,2) NULL DEFAULT '0.00',
  `domicilio_gratis_desde` DECIMAL(12,2) NULL DEFAULT NULL,
  `tiempo_entrega_minutos` INT NULL DEFAULT '30',
  `moneda` VARCHAR(10) NULL DEFAULT 'COP',
  `zona_horaria` VARCHAR(50) NULL DEFAULT 'America/Bogota',
  `payu_api_key` VARCHAR(255) NULL DEFAULT NULL,
  `payu_merchant_id` VARCHAR(100) NULL DEFAULT NULL,
  `payu_account_id` VARCHAR(100) NULL DEFAULT NULL,
  `payu_modo` ENUM('sandbox', 'produccion') NULL DEFAULT 'sandbox',
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `color_primario` VARCHAR(7) NULL DEFAULT NULL,
  `color_secundario` VARCHAR(7) NULL DEFAULT NULL,
  `color_texto` VARCHAR(7) NULL DEFAULT NULL,
  `color_fondo` VARCHAR(7) NULL DEFAULT NULL,
  `fuente_principal` VARCHAR(100) NULL DEFAULT NULL,
  `simbolo_moneda` VARCHAR(5) NULL DEFAULT NULL,
  `posicion_simbolo_moneda` VARCHAR(20) NULL DEFAULT NULL,
  `separador_decimal` VARCHAR(1) NULL DEFAULT NULL,
  `separador_miles` VARCHAR(1) NULL DEFAULT NULL,
  `idioma_por_defecto` VARCHAR(5) NULL DEFAULT NULL,
  `formato_fecha` VARCHAR(20) NULL DEFAULT NULL,
  `aplica_iva` TINYINT(1) NULL DEFAULT NULL,
  `acepta_efectivo` TINYINT(1) NULL DEFAULT NULL,
  `acepta_tarjeta_credito` TINYINT(1) NULL DEFAULT NULL,
  `acepta_tarjeta_debito` TINYINT(1) NULL DEFAULT NULL,
  `acepta_transferencia` TINYINT(1) NULL DEFAULT NULL,
  `acepta_pse` TINYINT(1) NULL DEFAULT NULL,
  `acepta_nequi` TINYINT(1) NULL DEFAULT NULL,
  `acepta_daviplata` TINYINT(1) NULL DEFAULT NULL,
  `acepta_payu` TINYINT(1) NULL DEFAULT NULL,
  `cuentas_bancarias` JSON NULL DEFAULT NULL,
  `monto_minimo_domicilio` DECIMAL(12,2) NULL DEFAULT NULL,
  `costo_domicilio_base` DECIMAL(12,2) NULL DEFAULT NULL,
  `tiempo_estimado_preparacion_min` INT NULL DEFAULT NULL,
  `tiempo_estimado_entrega_min` INT NULL DEFAULT NULL,
  `dias_programacion_adelantada` INT NULL DEFAULT NULL,
  `notificar_nueva_resena` TINYINT(1) NULL DEFAULT NULL,
  `canal_notificacion_pedidos` VARCHAR(20) NULL DEFAULT NULL,
  `sonido_notificacion` TINYINT(1) NULL DEFAULT NULL,
  `politica_privacidad` TEXT NULL DEFAULT NULL,
  `mensaje_agradecimiento` TEXT NULL DEFAULT NULL,
  `google_analytics_id` VARCHAR(50) NULL DEFAULT NULL,
  `facebook_pixel_id` VARCHAR(50) NULL DEFAULT NULL,
  `webhook_pedidos` VARCHAR(500) NULL DEFAULT NULL,
  `requiere_2fa_admin` TINYINT(1) NULL DEFAULT NULL,
  `sesion_max_minutos` INT NULL DEFAULT NULL,
  `modo_mantenimiento` TINYINT(1) NULL DEFAULT NULL,
  `mensaje_mantenimiento` TEXT NULL DEFAULT NULL,
  `iva` DECIMAL(5,2) NULL DEFAULT NULL,
  `prefijo_factura` VARCHAR(10) NULL DEFAULT NULL,
  `consecutivo_factura` INT NULL DEFAULT NULL,
  `pie_pagina_factura` TEXT NULL DEFAULT NULL,
  `monto_minimo_pedido` DECIMAL(12,2) NULL DEFAULT NULL,
  `notificar_nuevo_pedido` TINYINT(1) NULL DEFAULT NULL,
  `notificar_stock_bajo` TINYINT(1) NULL DEFAULT NULL,
  `mensaje_bienvenida` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_configuracion`),
  UNIQUE INDEX `id_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_config_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`conversaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`conversaciones` (
  `id_conversacion` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `tipo` ENUM('interna', 'cliente') NOT NULL DEFAULT 'cliente',
  `asunto` VARCHAR(255) NULL DEFAULT NULL,
  `estado` ENUM('activa', 'archivada', 'cerrada') NOT NULL DEFAULT 'activa',
  `ultimo_mensaje` TEXT NULL DEFAULT NULL,
  `fecha_ultimo_mensaje` DATETIME NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_conversacion`),
  INDEX `idx_conversacion_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_conversacion_tipo` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_conversacion_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`direcciones_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`direcciones_cliente` (
  `id_direccion` CHAR(36) NOT NULL,
  `id_cliente` CHAR(36) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` TEXT NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `departamento` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(20) NULL DEFAULT NULL,
  `latitud` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitud` DECIMAL(11,8) NULL DEFAULT NULL,
  `indicaciones` TEXT NULL DEFAULT NULL,
  `es_principal` TINYINT(1) NOT NULL DEFAULT '0',
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_direccion`),
  INDEX `idx_direccion_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `prodven_db`.`clientes` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`pedidos` (
  `id_pedido` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_cliente` CHAR(36) NOT NULL,
  `id_direccion` CHAR(36) NULL DEFAULT NULL,
  `id_promocion` CHAR(36) NULL DEFAULT NULL,
  `numero_pedido` VARCHAR(50) NOT NULL,
  `tipo_entrega` ENUM('domicilio', 'recogida', 'en_sitio') NOT NULL DEFAULT 'domicilio',
  `tipo_pago` ENUM('digital', 'contra_entrega', 'mixto') NOT NULL DEFAULT 'digital',
  `estado` ENUM('pendiente', 'confirmado', 'en_preparacion', 'en_camino', 'entregado', 'cancelado', 'reembolsado') NOT NULL DEFAULT 'pendiente',
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `descuento` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `impuestos` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `costo_domicilio` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `total` DECIMAL(12,2) NOT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `direccion_envio` TEXT NULL DEFAULT NULL,
  `latitud_entrega` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitud_entrega` DECIMAL(11,8) NULL DEFAULT NULL,
  `fecha_pedido` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_confirmacion` DATETIME NULL DEFAULT NULL,
  `fecha_entrega_real` DATETIME NULL DEFAULT NULL,
  `creado_por` CHAR(36) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pedido`),
  UNIQUE INDEX `numero_pedido` (`numero_pedido` ASC) VISIBLE,
  INDEX `fk_pedido_direccion` (`id_direccion` ASC) VISIBLE,
  INDEX `fk_pedido_promocion` (`id_promocion` ASC) VISIBLE,
  INDEX `fk_pedido_creado_por` (`creado_por` ASC) VISIBLE,
  INDEX `idx_pedido_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_pedido_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_pedido_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_pedido_numero` (`numero_pedido` ASC) VISIBLE,
  INDEX `idx_pedido_fecha_estado_empresa` (`fecha_pedido` ASC, `estado` ASC, `id_empresa` ASC) VISIBLE,
  INDEX `idx_pedido_empresa_fecha` (`id_empresa` ASC, `fecha_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `prodven_db`.`clientes` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_creado_por`
    FOREIGN KEY (`creado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_direccion`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `prodven_db`.`direcciones_cliente` (`id_direccion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_promocion`
    FOREIGN KEY (`id_promocion`)
    REFERENCES `prodven_db`.`promociones` (`id_promocion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`detalles_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`detalles_pedido` (
  `id_detalle` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(12,2) NOT NULL,
  `descuento` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `subtotal` DECIMAL(12,2) NOT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_detalle_producto` (`id_producto` ASC) VISIBLE,
  INDEX `idx_detalle_pedido` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`domiciliarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`domiciliarios` (
  `id_domiciliario` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NOT NULL,
  `tipo_vehiculo` ENUM('moto', 'carro', 'bicicleta', 'pie') NOT NULL DEFAULT 'moto',
  `placa` VARCHAR(20) NULL DEFAULT NULL,
  `documento_identidad` VARCHAR(20) NOT NULL,
  `licencia_conduccion` VARCHAR(50) NULL DEFAULT NULL,
  `disponible` TINYINT(1) NOT NULL DEFAULT '1',
  `ultima_latitud` DECIMAL(10,8) NULL DEFAULT NULL,
  `ultima_longitud` DECIMAL(11,8) NULL DEFAULT NULL,
  `ultima_actualizacion` DATETIME NULL DEFAULT NULL,
  `calificacion_promedio` DECIMAL(3,2) NOT NULL DEFAULT '0.00',
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_domiciliario`),
  UNIQUE INDEX `uk_domiciliario_empresa_usuario` (`id_empresa` ASC, `id_usuario` ASC) VISIBLE,
  INDEX `fk_domiciliario_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_domiciliario_disponible` (`id_empresa` ASC, `disponible` ASC) VISIBLE,
  CONSTRAINT `fk_domiciliario_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_domiciliario_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`facturas` (
  `id_factura` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `numero_factura` VARCHAR(50) NOT NULL,
  `fecha_emision` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_vencimiento` DATETIME NULL DEFAULT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `impuestos` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `estado` ENUM('pagada', 'pendiente', 'vencida', 'anulada') NOT NULL DEFAULT 'pendiente',
  `creado_por` CHAR(36) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_factura`),
  UNIQUE INDEX `id_pedido` (`id_pedido` ASC) VISIBLE,
  UNIQUE INDEX `numero_factura` (`numero_factura` ASC) VISIBLE,
  INDEX `fk_factura_creado_por` (`creado_por` ASC) VISIBLE,
  INDEX `idx_factura_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_factura_estado` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_factura_creado_por`
    FOREIGN KEY (`creado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`imagenes_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`imagenes_producto` (
  `id_imagen` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NOT NULL,
  `url` TEXT NOT NULL,
  `es_principal` TINYINT(1) NOT NULL DEFAULT '0',
  `orden` INT NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_imagen`),
  INDEX `idx_imagen_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_imagen_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`items_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`items_carrito` (
  `id_item` CHAR(36) NOT NULL,
  `id_carrito` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NOT NULL,
  `cantidad` INT NOT NULL DEFAULT '1',
  `precio_unitario` DECIMAL(12,2) NOT NULL,
  `descuento` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `subtotal` DECIMAL(12,2) NOT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_item`),
  INDEX `fk_item_producto` (`id_producto` ASC) VISIBLE,
  INDEX `idx_item_carrito` (`id_carrito` ASC) VISIBLE,
  CONSTRAINT `fk_item_carrito`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `prodven_db`.`carrito` (`id_carrito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`logs_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`logs_actividad` (
  `id_log` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NULL DEFAULT NULL,
  `id_empresa` CHAR(36) NULL DEFAULT NULL,
  `accion` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `dispositivo` VARCHAR(255) NULL DEFAULT NULL,
  `datos_extra` JSON NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  INDEX `idx_log_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_log_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_log_fecha` (`fecha_creacion` ASC) VISIBLE,
  INDEX `idx_log_actividad_fecha` (`fecha_creacion` ASC, `id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_log_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`ordenes_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`ordenes_produccion` (
  `id_produccion` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` ENUM('programada', 'en_proceso', 'completada', 'cancelada') NOT NULL DEFAULT 'programada',
  `fecha_programada` DATETIME NOT NULL,
  `fecha_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `creado_por` CHAR(36) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_produccion`),
  INDEX `fk_produccion_producto` (`id_producto` ASC) VISIBLE,
  INDEX `fk_produccion_creado` (`creado_por` ASC) VISIBLE,
  INDEX `idx_produccion_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_produccion_estado` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_produccion_creado`
    FOREIGN KEY (`creado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produccion_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produccion_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`materiales_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`materiales_produccion` (
  `id_material` CHAR(36) NOT NULL,
  `id_produccion` CHAR(36) NOT NULL,
  `id_producto_material` CHAR(36) NOT NULL,
  `cantidad_requerida` DECIMAL(12,2) NOT NULL,
  `cantidad_consumida` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `unidad` VARCHAR(30) NOT NULL DEFAULT 'unidad',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_material`),
  INDEX `fk_material_producto` (`id_producto_material` ASC) VISIBLE,
  INDEX `idx_material_produccion` (`id_produccion` ASC) VISIBLE,
  CONSTRAINT `fk_material_produccion`
    FOREIGN KEY (`id_produccion`)
    REFERENCES `prodven_db`.`ordenes_produccion` (`id_produccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_material_producto`
    FOREIGN KEY (`id_producto_material`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`mensajes` (
  `id_mensaje` CHAR(36) NOT NULL,
  `id_conversacion` CHAR(36) NOT NULL,
  `id_remitente` CHAR(36) NOT NULL,
  `contenido` TEXT NOT NULL,
  `tipo_contenido` ENUM('texto', 'imagen', 'archivo', 'audio', 'video') NOT NULL DEFAULT 'texto',
  `url_archivo` TEXT NULL DEFAULT NULL,
  `leido` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_lectura` DATETIME NULL DEFAULT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_mensaje`),
  INDEX `idx_mensaje_conversacion` (`id_conversacion` ASC) VISIBLE,
  INDEX `idx_mensaje_remitente` (`id_remitente` ASC) VISIBLE,
  INDEX `idx_mensaje_conversacion_fecha` (`id_conversacion` ASC, `fecha_creacion` ASC) VISIBLE,
  CONSTRAINT `fk_mensaje_conversacion`
    FOREIGN KEY (`id_conversacion`)
    REFERENCES `prodven_db`.`conversaciones` (`id_conversacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mensaje_remitente`
    FOREIGN KEY (`id_remitente`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`metodos_pago_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`metodos_pago_vendedor` (
  `id_metodo` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `metodo` ENUM('tarjeta_credito', 'tarjeta_debito', 'pse', 'efectivo', 'billetera_digital', 'contra_entrega') NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_metodo`),
  UNIQUE INDEX `uk_empresa_metodo` (`id_empresa` ASC, `metodo` ASC) VISIBLE,
  INDEX `idx_metodo_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_metodo_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`movimientos_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`movimientos_inventario` (
  `id_movimiento` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NOT NULL,
  `cantidad` INT NOT NULL,
  `tipo_movimiento` ENUM('entrada', 'salida', 'ajuste', 'devolucion') NOT NULL,
  `tabla_referencia` VARCHAR(50) NULL DEFAULT NULL,
  `id_referencia` CHAR(36) NULL DEFAULT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `creado_por` CHAR(36) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_movimiento`),
  INDEX `fk_movimiento_usuario` (`creado_por` ASC) VISIBLE,
  INDEX `idx_movimiento_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_movimiento_producto` (`id_producto` ASC) VISIBLE,
  INDEX `idx_movimiento_fecha` (`fecha_creacion` ASC, `id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movimiento_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movimiento_usuario`
    FOREIGN KEY (`creado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`notificaciones` (
  `id_notificacion` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NULL DEFAULT NULL,
  `titulo` VARCHAR(150) NOT NULL,
  `mensaje` TEXT NOT NULL,
  `tipo` ENUM('pedido', 'pago', 'inventario', 'mensaje', 'sistema', 'promocion') NOT NULL DEFAULT 'sistema',
  `canal` ENUM('email', 'sms', 'push', 'sistema') NOT NULL DEFAULT 'sistema',
  `leida` TINYINT(1) NOT NULL DEFAULT '0',
  `url_accion` TEXT NULL DEFAULT NULL,
  `fecha_envio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_notificacion`),
  INDEX `idx_notificacion_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_notificacion_leida` (`leida` ASC) VISIBLE,
  INDEX `idx_notificacion_usuario_leida` (`id_usuario` ASC, `leida` ASC, `fecha_envio` ASC) VISIBLE,
  CONSTRAINT `fk_notificacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`notificaciones_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`notificaciones_push` (
  `id_push` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NOT NULL,
  `token_dispositivo` TEXT NOT NULL,
  `plataforma` ENUM('android', 'ios', 'web') NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_push`),
  UNIQUE INDEX `idx_unique_usuario_token` (`id_usuario` ASC, `token_dispositivo`(255) ASC) VISIBLE,
  INDEX `idx_push_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_push_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`pagos` (
  `id_pago` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `metodo` ENUM('tarjeta_credito', 'tarjeta_debito', 'pse', 'efectivo', 'billetera_digital', 'contra_entrega') NOT NULL,
  `estado` ENUM('completado', 'fallido', 'pendiente', 'reembolsado', 'en_proceso') NOT NULL DEFAULT 'pendiente',
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_pago` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` CHAR(36) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `fk_pago_creado_por` (`creado_por` ASC) VISIBLE,
  INDEX `idx_pago_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `idx_pago_estado` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_pago_creado_por`
    FOREIGN KEY (`creado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pago_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pago_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`participantes_conversacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`participantes_conversacion` (
  `id_participante` CHAR(36) NOT NULL,
  `id_conversacion` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NOT NULL,
  `rol` ENUM('admin', 'agente', 'cliente') NOT NULL DEFAULT 'cliente',
  `fecha_ingreso` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_ultimo_visto` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_participante`),
  UNIQUE INDEX `uk_conversacion_usuario` (`id_conversacion` ASC, `id_usuario` ASC) VISIBLE,
  INDEX `fk_participante_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_participante_conversacion` (`id_conversacion` ASC) VISIBLE,
  CONSTRAINT `fk_participante_conversacion`
    FOREIGN KEY (`id_conversacion`)
    REFERENCES `prodven_db`.`conversaciones` (`id_conversacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_participante_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`pedidos_programados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`pedidos_programados` (
  `id_programado` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `fecha_programada` DATETIME NOT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'confirmado', 'procesado', 'cancelado') NOT NULL DEFAULT 'pendiente',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_programado`),
  UNIQUE INDEX `id_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `idx_programado_fecha` (`fecha_programada` ASC) VISIBLE,
  CONSTRAINT `fk_programado_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`reembolsos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`reembolsos` (
  `id_reembolso` CHAR(36) NOT NULL,
  `id_pago` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `motivo` TEXT NOT NULL,
  `estado` ENUM('solicitado', 'aprobado', 'procesado', 'rechazado') NOT NULL DEFAULT 'solicitado',
  `referencia_payu` VARCHAR(100) NULL DEFAULT NULL,
  `aprobado_por` CHAR(36) NULL DEFAULT NULL,
  `fecha_aprobacion` DATETIME NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_reembolso`),
  INDEX `fk_reembolso_pago` (`id_pago` ASC) VISIBLE,
  INDEX `fk_reembolso_aprobado` (`aprobado_por` ASC) VISIBLE,
  INDEX `idx_reembolso_pedido` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_reembolso_aprobado`
    FOREIGN KEY (`aprobado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reembolso_pago`
    FOREIGN KEY (`id_pago`)
    REFERENCES `prodven_db`.`pagos` (`id_pago`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reembolso_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`registros_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`registros_auditoria` (
  `id_registro` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NULL DEFAULT NULL,
  `entidad` VARCHAR(100) NOT NULL,
  `id_entidad` CHAR(36) NOT NULL,
  `accion` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `valor_anterior` JSON NULL DEFAULT NULL,
  `valor_nuevo` JSON NULL DEFAULT NULL,
  `realizado_por` CHAR(36) NULL DEFAULT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_accion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_registro`),
  INDEX `fk_auditoria_usuario` (`realizado_por` ASC) VISIBLE,
  INDEX `idx_auditoria_entidad` (`entidad` ASC) VISIBLE,
  INDEX `idx_auditoria_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_auditoria_fecha` (`fecha_accion` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuario`
    FOREIGN KEY (`realizado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`reportes` (
  `id_reporte` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `parametros` JSON NULL DEFAULT NULL,
  `generado_por` CHAR(36) NOT NULL,
  `estado` ENUM('generado', 'en_proceso', 'error', 'cancelado') NOT NULL DEFAULT 'en_proceso',
  `enlace_archivo` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_reporte`),
  INDEX `fk_reporte_usuario` (`generado_por` ASC) VISIBLE,
  INDEX `idx_reporte_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_reporte_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reporte_usuario`
    FOREIGN KEY (`generado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`resenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`resenas` (
  `id_resena` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NULL DEFAULT NULL,
  `id_cliente` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NULL DEFAULT NULL,
  `calificacion` TINYINT NOT NULL,
  `titulo` VARCHAR(150) NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT '1',
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resena`),
  INDEX `fk_resena_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_resena_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `idx_resena_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `idx_resena_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_resena_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `prodven_db`.`clientes` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_resena_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_resena_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_resena_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`reservas_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`reservas_stock` (
  `id_reserva` CHAR(36) NOT NULL,
  `id_producto` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` ENUM('activa', 'confirmada', 'cancelada', 'expirada') NOT NULL DEFAULT 'activa',
  `fecha_expiracion` DATETIME NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_reserva`),
  INDEX `idx_reserva_producto_estado` (`id_producto` ASC, `estado` ASC) VISIBLE,
  INDEX `idx_reserva_expiracion` (`fecha_expiracion` ASC) VISIBLE,
  INDEX `idx_reserva_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `idx_reserva_activas` (`id_producto` ASC, `estado` ASC, `fecha_expiracion` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prodven_db`.`productos` (`id_producto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`seguimiento_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`seguimiento_pedido` (
  `id_seguimiento` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `estado` ENUM('pendiente', 'confirmado', 'en_preparacion', 'en_camino', 'entregado', 'cancelado', 'reembolsado') NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `latitud` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitud` DECIMAL(11,8) NULL DEFAULT NULL,
  `registrado_por` CHAR(36) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_seguimiento`),
  INDEX `fk_seguimiento_usuario` (`registrado_por` ASC) VISIBLE,
  INDEX `idx_seguimiento_pedido` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seguimiento_usuario`
    FOREIGN KEY (`registrado_por`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`suscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`suscripciones` (
  `id_suscripcion` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `plan` VARCHAR(20) NULL DEFAULT NULL,
  `precio_mensual` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `estado` ENUM('activa', 'vencida', 'cancelada', 'pendiente') NOT NULL DEFAULT 'activa',
  `referencia_pago` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `permite` VARCHAR(45) NULL DEFAULT NULL,
  `moneda` VARCHAR(3) NULL DEFAULT NULL,
  `ciclo` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_proximo_cobro` DATETIME NULL DEFAULT NULL,
  `renovacion_automatica` TINYINT(1) NULL DEFAULT NULL,
  `limite_productos` INT NULL DEFAULT NULL,
  `limite_usuarios` INT NULL DEFAULT NULL,
  `limite_almacenamiento_mb` INT NULL DEFAULT NULL,
  `limite_pedidos_mensuales` INT NULL DEFAULT NULL,
  `permite_marketplace` TINYINT(1) NULL DEFAULT NULL,
  `permite_reportes_avanzados` TINYINT(1) NULL DEFAULT NULL,
  `permite_integraciones_externas` TINYINT(1) NULL DEFAULT NULL,
  `permite_api_externa` TINYINT(1) NULL DEFAULT NULL,
  `permite_multiples_sucursales` TINYINT(1) NULL DEFAULT NULL,
  `permite_app_movil_domiciliarios` TINYINT(1) NULL DEFAULT NULL,
  `soporte_prioritario` TINYINT(1) NULL DEFAULT NULL,
  `dias_prueba` INT NULL DEFAULT NULL,
  `en_periodo_prueba` TINYINT(1) NULL DEFAULT NULL,
  `fecha_fin_prueba` DATETIME NULL DEFAULT NULL,
  `notas_admin` TEXT NULL DEFAULT NULL,
  `cancelada_por` CHAR(36) NULL DEFAULT NULL,
  `fecha_cancelacion` DATETIME NULL DEFAULT NULL,
  `motivo_cancelacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_suscripcion`),
  INDEX `idx_suscripcion_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_suscripcion_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`tokens_acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`tokens_acceso` (
  `id_token` CHAR(36) NOT NULL,
  `id_usuario` CHAR(36) NOT NULL,
  `token` TEXT NOT NULL,
  `tipo` ENUM('access', 'refresh') NOT NULL DEFAULT 'access',
  `ip_origen` VARCHAR(45) NULL DEFAULT NULL,
  `dispositivo` VARCHAR(255) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_expiracion` DATETIME NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_token`),
  INDEX `idx_token_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_token_expiracion` (`fecha_expiracion` ASC) VISIBLE,
  CONSTRAINT `fk_token_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`transacciones_payu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`transacciones_payu` (
  `id_transaccion` CHAR(36) NOT NULL,
  `id_pago` CHAR(36) NOT NULL,
  `payu_order_id` VARCHAR(100) NULL DEFAULT NULL,
  `payu_transaction_id` VARCHAR(100) NULL DEFAULT NULL,
  `payu_reference` VARCHAR(100) NOT NULL,
  `estado_payu` VARCHAR(50) NOT NULL,
  `codigo_respuesta` VARCHAR(50) NULL DEFAULT NULL,
  `mensaje_respuesta` TEXT NULL DEFAULT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `moneda` VARCHAR(10) NOT NULL DEFAULT 'COP',
  `ip_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `datos_completos` JSON NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_transaccion`),
  INDEX `idx_transaccion_payu_reference` (`payu_reference` ASC) VISIBLE,
  INDEX `idx_transaccion_pago` (`id_pago` ASC) VISIBLE,
  CONSTRAINT `fk_transaccion_pago`
    FOREIGN KEY (`id_pago`)
    REFERENCES `prodven_db`.`pagos` (`id_pago`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`ubicacion_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`ubicacion_pedido` (
  `id_ubicacion` CHAR(36) NOT NULL,
  `id_pedido` CHAR(36) NOT NULL,
  `id_domiciliario` CHAR(36) NOT NULL,
  `latitud` DECIMAL(10,8) NOT NULL,
  `longitud` DECIMAL(11,8) NOT NULL,
  `velocidad` DECIMAL(5,2) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_ubicacion`),
  INDEX `fk_ubicacion_domiciliario` (`id_domiciliario` ASC) VISIBLE,
  INDEX `idx_ubicacion_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `idx_ubicacion_fecha` (`fecha_registro` ASC, `id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_ubicacion_domiciliario`
    FOREIGN KEY (`id_domiciliario`)
    REFERENCES `prodven_db`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ubicacion_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `prodven_db`.`pedidos` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `prodven_db`.`zonas_cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodven_db`.`zonas_cobertura` (
  `id_zona` CHAR(36) NOT NULL,
  `id_empresa` CHAR(36) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo` ENUM('circulo', 'poligono', 'ciudad', 'barrio') NOT NULL DEFAULT 'circulo',
  `latitud_centro` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitud_centro` DECIMAL(11,8) NULL DEFAULT NULL,
  `radio_km` DECIMAL(5,2) NULL DEFAULT NULL,
  `poligono_geojson` JSON NULL DEFAULT NULL,
  `costo_adicional` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `tiempo_estimado_min` INT NOT NULL DEFAULT '30',
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_zona`),
  INDEX `idx_zona_empresa_activo` (`id_empresa` ASC, `activo` ASC) VISIBLE,
  CONSTRAINT `fk_zona_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `prodven_db`.`empresas` (`id_empresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `prodven_db` ;

-- -----------------------------------------------------
-- procedure sp_limpiar_carritos_abandonados
-- -----------------------------------------------------

DELIMITER $$
USE `prodven_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_limpiar_carritos_abandonados`()
BEGIN
    UPDATE carrito
    SET estado = 'abandonado'
    WHERE estado = 'activo'
      AND fecha_actualizacion < DATE_SUB(NOW(), INTERVAL 7 DAY);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_limpiar_reservas_expiradas
-- -----------------------------------------------------

DELIMITER $$
USE `prodven_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_limpiar_reservas_expiradas`()
BEGIN
    -- Primero marcar como expiradas
    UPDATE reservas_stock
    SET estado = 'expirada'
    WHERE estado = 'activa'
      AND fecha_expiracion < NOW();
    
    -- Devolver stock solo de reservas recién expiradas (última hora)
    -- para evitar procesar la misma reserva dos veces
    UPDATE productos p
    INNER JOIN reservas_stock r ON p.id_producto = r.id_producto
    SET p.cantidad_stock = p.cantidad_stock + r.cantidad
    WHERE r.estado = 'expirada'
      AND r.fecha_expiracion >= DATE_SUB(NOW(), INTERVAL 1 HOUR);
END$$

DELIMITER ;
USE `prodven_db`;

DELIMITER $$
USE `prodven_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `prodven_db`.`trg_actualizar_calificacion_promedio`
AFTER INSERT ON `prodven_db`.`resenas`
FOR EACH ROW
BEGIN
    DECLARE nuevo_promedio DECIMAL(3,2);
    DECLARE total_resenas INT;
    
    SELECT AVG(calificacion), COUNT(*)
    INTO nuevo_promedio, total_resenas
    FROM resenas
    WHERE id_producto = NEW.id_producto AND visible = 1 AND eliminado = 0;
    
    UPDATE productos
    SET calificacion_promedio = nuevo_promedio,
        total_resenas = total_resenas
    WHERE id_producto = NEW.id_producto;
END$$

USE `prodven_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `prodven_db`.`trg_actualizar_calificacion_update`
AFTER UPDATE ON `prodven_db`.`resenas`
FOR EACH ROW
BEGIN
    DECLARE nuevo_promedio DECIMAL(3,2);
    DECLARE total_resenas INT;
    
    IF OLD.visible != NEW.visible OR OLD.eliminado != NEW.eliminado OR OLD.calificacion != NEW.calificacion THEN
        SELECT AVG(calificacion), COUNT(*)
        INTO nuevo_promedio, total_resenas
        FROM resenas
        WHERE id_producto = NEW.id_producto AND visible = 1 AND eliminado = 0;
        
        UPDATE productos
        SET calificacion_promedio = nuevo_promedio,
            total_resenas = total_resenas
        WHERE id_producto = NEW.id_producto;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
